#!/bin/sh +x
SCR_PATH=`readlink -f "$0"`
SCR_DIR=`dirname "$SCR_PATH"`
SOURCE=$SCR_DIR/datasheets.csv
which awk > /dev/null
if [ $? -eq 0 ]; then
	which tac > /dev/null
	if [ $? -eq 0 ]; then
		if [ -f $SOURCE ]; then
			td=`cat /dev/urandom | tr -cd 'a-f0-9' | head -c 32`
			td="/dev/shm/$td/"
			mkdir $td > /dev/null 2>&1
			if [ -d $td ]; then
				#if [ $# -eq 2 ] && [ ! -z "$1" ] && [ ! -z "$2" ]; then
				count=`ls -1 *.sch 2>/dev/null | wc -l`
				if [ $count != 0 ]; then
					for f in *.sch; do
						grep -q "EESchema Schematic File Version 2" $f || grep -q "EESchema Schematic File Version 3" $f ||
						grep -q "EESchema Schematic File Version 4" $f
						if [ $? -eq 0 ]; then
							tf=`cat /dev/urandom | tr -cd 'a-f0-9' | head -c 32`
							tf="$td$tf"
							cp $f $tf
							while IFS=, read -r MF PN DS; do
								if [ ! -z $MF ] && [ ! -z $PN ] && [ ! -z $DS ]; then
									count=`grep -c "F 7 \"$PN\"" $f`
									if [ $count != 0 ]; then
										#echo "$PN found in $f"
										mv $tf $tf.ydk
										cat $tf.ydk | tac | awk -v PN=$PN -v DS=$DS 'BEGIN {FS=OFS=" ";}{if($1=="F"&&$2=="7"){if($3=="\""PN"\""){edit=1;}else{edit=0;}}}{if(edit&&$1=="F"&&$2=="3"){$3="\""DS"\"";edit=0}print; }' | tac > $tf
										rm $tf.ydk
									fi
								fi
							done < $SOURCE
							#cat $tf
							dc=`diff -by --suppress-common-lines $f $tf | wc -l`
							if [ $dc != 0 ]; then
								echo "Added / edited $dc links to $f."
								mv $f $f.ydk
								mv $tf $f
							fi
						else
							echo "Wrong file type. $f should be EESchema Schematic File Version 2 or greater."
						fi
					done
				else
					echo "No sch file found in current directory."
				fi
				#else
				#	echo Usage: $0
				#fi
				rm -fr $td
			else
				echo "Cannot create temporary directory $td."
			fi
		else
			echo "Cannot read $SOURCE."
		fi
	else
		echo "Please install tac."
	fi
else
	echo "Please install awk."
fi